defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- datamodule: single
- hardware: example
- graph: multi_scale
- model: gnn
- training: default
- _self_


# set to true to switch on config validation
config_validation: True

training:
  max_steps: 1000
  optimizer:
    name: AdEMAMix
    betas: [0.9, 0.999, 0.9999]
    alpha: 8.0
    beta3_warmup: ${training.max_steps}
    alpha_warmup: ${training.max_steps}
    eps: 1.0e-8
    weight_decay: 0.1
